export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';
export const SET_USER_AUTHENTICATED = 'SET_USER_AUTHENTICATED';
export const SET_USER_CURRENT = 'SET_USER_CURRENT';
export const SET_USER_LIST = 'SET_USER_LIST';
